spring.application.name=autoRepairShop_SpringBoot

# ⚙️ Configuración de Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# 🚀 Puerto dinámico para Railway
server.port=${PORT:8080}
