spring.application.name=autoRepairShop_SpringBoot

# 🔗 Conexión a la base de datos MySQL en Railway
spring.datasource.url=jdbc:mysql://reseau.proxy.rlwy.net:48918/railway?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=gmBaLbCZEGxGAzcsrKrMkWcsxavTcJqQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ⚙️ Configuración de Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# 🚀 Puerto dinámico para Railway
server.port=${PORT:8080}
